/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HistoryCallIdRouteImport } from './routes/history.$callId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MypageRouteImport } from './routes/mypage'
import { Route as MypageEditRouteImport } from './routes/mypage.edit'
import { Route as MypagePasswordRouteImport } from './routes/mypage.password'
import { Route as MypageSettingsRouteImport } from './routes/mypage.settings'
import { Route as WalletChargeRouteImport } from './routes/wallet.charge'
import { Route as OtomoOtomoIdRouteImport } from './routes/otomo.$otomoId'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as CallCallIdRouteImport } from './routes/call.$callId'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiTqTodosRouteImport } from './routes/demo/api.tq-todos'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as CallCallIdSummaryRouteImport } from './routes/call.$callId.summary'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as OtomoHomeRouteImport } from './routes/otomo-home'
import { Route as OtomoCallIncomingRouteImport } from './routes/otomo-call.incoming'
import { Route as OtomoCallActiveRouteImport } from './routes/otomo-call.active'
import { Route as OtomoCallSummaryRouteImport } from './routes/otomo-call.summary'
import { Route as OtomoDashboardRevenueRouteImport } from './routes/otomo-dashboard.revenue'
import { Route as OtomoScheduleRouteImport } from './routes/otomo-schedule'
import { Route as OtomoReviewsRouteImport } from './routes/otomo-reviews'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryCallIdRoute = HistoryCallIdRouteImport.update({
  id: '/history/$callId',
  path: '/history/$callId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageRoute = MypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageEditRoute = MypageEditRouteImport.update({
  id: '/mypage/edit',
  path: '/mypage/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MypagePasswordRoute = MypagePasswordRouteImport.update({
  id: '/mypage/password',
  path: '/mypage/password',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageSettingsRoute = MypageSettingsRouteImport.update({
  id: '/mypage/settings',
  path: '/mypage/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletChargeRoute = WalletChargeRouteImport.update({
  id: '/charge',
  path: '/charge',
  getParentRoute: () => WalletRoute,
} as any)
const OtomoOtomoIdRoute = OtomoOtomoIdRouteImport.update({
  id: '/otomo/$otomoId',
  path: '/otomo/$otomoId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCallIdRoute = CallCallIdRouteImport.update({
  id: '/call/$callId',
  path: '/call/$callId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTqTodosRoute = DemoApiTqTodosRouteImport.update({
  id: '/demo/api/tq-todos',
  path: '/demo/api/tq-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const CallCallIdSummaryRoute = CallCallIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => CallCallIdRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const OtomoHomeRoute = OtomoHomeRouteImport.update({
  id: '/otomo-home',
  path: '/otomo-home',
  getParentRoute: () => rootRouteImport,
} as any)
const OtomoCallIncomingRoute = OtomoCallIncomingRouteImport.update({
  id: '/otomo-call/incoming',
  path: '/otomo-call/incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const OtomoCallActiveRoute = OtomoCallActiveRouteImport.update({
  id: '/otomo-call/active',
  path: '/otomo-call/active',
  getParentRoute: () => rootRouteImport,
} as any)
const OtomoCallSummaryRoute = OtomoCallSummaryRouteImport.update({
  id: '/otomo-call/summary',
  path: '/otomo-call/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const OtomoDashboardRevenueRoute = OtomoDashboardRevenueRouteImport.update({
  id: '/otomo-dashboard/revenue',
  path: '/otomo-dashboard/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const OtomoScheduleRoute = OtomoScheduleRouteImport.update({
  id: '/otomo-schedule',
  path: '/otomo-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const OtomoReviewsRoute = OtomoReviewsRouteImport.update({
  id: '/otomo-reviews',
  path: '/otomo-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mypage': typeof MypageRoute
  '/mypage/edit': typeof MypageEditRoute
  '/mypage/settings': typeof MypageSettingsRoute
  '/mypage/password': typeof MypagePasswordRoute
  '/history': typeof HistoryRoute
  '/history/$callId': typeof HistoryCallIdRoute
  '/wallet': typeof WalletRouteWithChildren
  '/call/$callId': typeof CallCallIdRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/otomo/$otomoId': typeof OtomoOtomoIdRoute
  '/wallet/charge': typeof WalletChargeRoute
  '/call/$callId/summary': typeof CallCallIdSummaryRoute
  '/otomo-home': typeof OtomoHomeRoute
  '/otomo-call/incoming': typeof OtomoCallIncomingRoute
  '/otomo-call/active': typeof OtomoCallActiveRoute
  '/otomo-call/summary': typeof OtomoCallSummaryRoute
  '/otomo-dashboard/revenue': typeof OtomoDashboardRevenueRoute
  '/otomo-schedule': typeof OtomoScheduleRoute
  '/otomo-reviews': typeof OtomoReviewsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mypage': typeof MypageRoute
  '/mypage/edit': typeof MypageEditRoute
  '/mypage/settings': typeof MypageSettingsRoute
  '/mypage/password': typeof MypagePasswordRoute
  '/history': typeof HistoryRoute
  '/history/$callId': typeof HistoryCallIdRoute
  '/wallet': typeof WalletRouteWithChildren
  '/call/$callId': typeof CallCallIdRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/otomo/$otomoId': typeof OtomoOtomoIdRoute
  '/wallet/charge': typeof WalletChargeRoute
  '/call/$callId/summary': typeof CallCallIdSummaryRoute
  '/otomo-home': typeof OtomoHomeRoute
  '/otomo-call/incoming': typeof OtomoCallIncomingRoute
  '/otomo-call/active': typeof OtomoCallActiveRoute
  '/otomo-call/summary': typeof OtomoCallSummaryRoute
  '/otomo-dashboard/revenue': typeof OtomoDashboardRevenueRoute
  '/otomo-schedule': typeof OtomoScheduleRoute
  '/otomo-reviews': typeof OtomoReviewsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mypage': typeof MypageRoute
  '/mypage/edit': typeof MypageEditRoute
  '/mypage/settings': typeof MypageSettingsRoute
  '/mypage/password': typeof MypagePasswordRoute
  '/history': typeof HistoryRoute
  '/history/$callId': typeof HistoryCallIdRoute
  '/wallet': typeof WalletRouteWithChildren
  '/call/$callId': typeof CallCallIdRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/otomo/$otomoId': typeof OtomoOtomoIdRoute
  '/wallet/charge': typeof WalletChargeRoute
  '/call/$callId/summary': typeof CallCallIdSummaryRoute
  '/otomo-home': typeof OtomoHomeRoute
  '/otomo-call/incoming': typeof OtomoCallIncomingRoute
  '/otomo-call/active': typeof OtomoCallActiveRoute
  '/otomo-call/summary': typeof OtomoCallSummaryRoute
  '/otomo-dashboard/revenue': typeof OtomoDashboardRevenueRoute
  '/otomo-schedule': typeof OtomoScheduleRoute
  '/otomo-reviews': typeof OtomoReviewsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/api/tq-todos': typeof DemoApiTqTodosRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mypage'
    | '/mypage/edit'
    | '/mypage/settings'
    | '/mypage/password'
    | '/history'
    | '/history/$callId'
    | '/wallet'
    | '/call/$callId'
    | '/demo/tanstack-query'
    | '/otomo/$otomoId'
    | '/wallet/charge'
    | '/call/$callId/summary'
    | '/otomo-home'
    | '/otomo-call/incoming'
    | '/otomo-call/active'
    | '/otomo-call/summary'
    | '/otomo-dashboard/revenue'
    | '/otomo-schedule'
    | '/otomo-reviews'
    | '/admin/login'
    | '/admin/users'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
  '/otomo-call/summary':
    | {
        id: '/otomo-call/summary'
        path: '/otomo-call/summary'
        fullPath: '/otomo-call/summary'
        preLoaderRoute: typeof OtomoCallSummaryRouteImport
        parentRoute: typeof rootRouteImport
      }
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mypage'
    | '/mypage/edit'
    | '/mypage/settings'
    | '/mypage/password'
    | '/history'
    | '/history/$callId'
    | '/wallet'
    | '/call/$callId'
    | '/demo/tanstack-query'
    | '/otomo/$otomoId'
    | '/wallet/charge'
    | '/call/$callId/summary'
    | '/otomo-home'
    | '/otomo-call/incoming'
    | '/otomo-call/active'
    | '/otomo-call/summary'
    | '/otomo-dashboard/revenue'
    | '/otomo-schedule'
    | '/otomo-reviews'
    | '/admin/login'
    | '/admin/users'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/mypage'
    | '/mypage/edit'
    | '/mypage/settings'
    | '/mypage/password'
    | '/history'
    | '/history/$callId'
    | '/wallet'
    | '/call/$callId'
    | '/demo/tanstack-query'
    | '/otomo/$otomoId'
    | '/wallet/charge'
    | '/call/$callId/summary'
    | '/otomo-home'
    | '/otomo-call/incoming'
    | '/otomo-call/active'
    | '/otomo-call/summary'
    | '/otomo-dashboard/revenue'
    | '/otomo-schedule'
    | '/otomo-reviews'
    | '/admin/login'
    | '/admin/users'
    | '/demo/api/names'
    | '/demo/api/tq-todos'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MypageRoute: typeof MypageRoute
  MypageEditRoute: typeof MypageEditRoute
  MypageSettingsRoute: typeof MypageSettingsRoute
  MypagePasswordRoute: typeof MypagePasswordRoute
  HistoryRoute: typeof HistoryRoute
  HistoryCallIdRoute: typeof HistoryCallIdRoute
  WalletRoute: typeof WalletRouteWithChildren
  CallCallIdRoute: typeof CallCallIdRouteWithChildren
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  OtomoOtomoIdRoute: typeof OtomoOtomoIdRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoApiTqTodosRoute: typeof DemoApiTqTodosRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
  OtomoHomeRoute: typeof OtomoHomeRoute
  OtomoCallIncomingRoute: typeof OtomoCallIncomingRoute
  OtomoCallActiveRoute: typeof OtomoCallActiveRoute
  OtomoCallSummaryRoute: typeof OtomoCallSummaryRoute
  OtomoDashboardRevenueRoute: typeof OtomoDashboardRevenueRoute
  OtomoScheduleRoute: typeof OtomoScheduleRoute
  OtomoReviewsRoute: typeof OtomoReviewsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage': {
      id: '/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/edit': {
      id: '/mypage/edit'
      path: '/mypage/edit'
      fullPath: '/mypage/edit'
      preLoaderRoute: typeof MypageEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/settings': {
      id: '/mypage/settings'
      path: '/mypage/settings'
      fullPath: '/mypage/settings'
      preLoaderRoute: typeof MypageSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$callId': {
      id: '/history/$callId'
      path: '/history/$callId'
      fullPath: '/history/$callId'
      preLoaderRoute: typeof HistoryCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/charge': {
      id: '/wallet/charge'
      path: '/charge'
      fullPath: '/wallet/charge'
      preLoaderRoute: typeof WalletChargeRouteImport
      parentRoute: typeof WalletRoute
    }
    '/otomo/$otomoId': {
      id: '/otomo/$otomoId'
      path: '/otomo/$otomoId'
      fullPath: '/otomo/$otomoId'
      preLoaderRoute: typeof OtomoOtomoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$callId': {
      id: '/call/$callId'
      path: '/call/$callId'
      fullPath: '/call/$callId'
      preLoaderRoute: typeof CallCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tq-todos': {
      id: '/demo/api/tq-todos'
      path: '/demo/api/tq-todos'
      fullPath: '/demo/api/tq-todos'
      preLoaderRoute: typeof DemoApiTqTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$callId/summary': {
      id: '/call/$callId/summary'
      path: '/summary'
      fullPath: '/call/$callId/summary'
      preLoaderRoute: typeof CallCallIdSummaryRouteImport
      parentRoute: typeof CallCallIdRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otomo-home': {
      id: '/otomo-home'
      path: '/otomo-home'
      fullPath: '/otomo-home'
      preLoaderRoute: typeof OtomoHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otomo-call/incoming': {
      id: '/otomo-call/incoming'
      path: '/otomo-call/incoming'
      fullPath: '/otomo-call/incoming'
      preLoaderRoute: typeof OtomoCallIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otomo-call/active': {
      id: '/otomo-call/active'
      path: '/otomo-call/active'
      fullPath: '/otomo-call/active'
      preLoaderRoute: typeof OtomoCallActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otomo-call/summary': {
      id: '/otomo-call/summary'
      path: '/otomo-call/summary'
      fullPath: '/otomo-call/summary'
      preLoaderRoute: typeof OtomoCallSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otomo-schedule': {
      id: '/otomo-schedule'
      path: '/otomo-schedule'
      fullPath: '/otomo-schedule'
      preLoaderRoute: typeof OtomoScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otomo-reviews': {
      id: '/otomo-reviews'
      path: '/otomo-reviews'
      fullPath: '/otomo-reviews'
      preLoaderRoute: typeof OtomoReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otomo-dashboard/revenue': {
      id: '/otomo-dashboard/revenue'
      path: '/otomo-dashboard/revenue'
      fullPath: '/otomo-dashboard/revenue'
      preLoaderRoute: typeof OtomoDashboardRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WalletRouteChildren {
  WalletChargeRoute: typeof WalletChargeRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletChargeRoute: WalletChargeRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

interface CallCallIdRouteChildren {
  CallCallIdSummaryRoute: typeof CallCallIdSummaryRoute
}

const CallCallIdRouteChildren: CallCallIdRouteChildren = {
  CallCallIdSummaryRoute: CallCallIdSummaryRoute,
}

const CallCallIdRouteWithChildren = CallCallIdRoute._addFileChildren(
  CallCallIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MypageRoute: MypageRoute,
  MypageEditRoute: MypageEditRoute,
  MypageSettingsRoute: MypageSettingsRoute,
  HistoryRoute: HistoryRoute,
  HistoryCallIdRoute: HistoryCallIdRoute,
  WalletRoute: WalletRouteWithChildren,
  CallCallIdRoute: CallCallIdRouteWithChildren,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  OtomoOtomoIdRoute: OtomoOtomoIdRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoApiTqTodosRoute: DemoApiTqTodosRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
  OtomoHomeRoute: OtomoHomeRoute,
  OtomoCallIncomingRoute: OtomoCallIncomingRoute,
  OtomoCallActiveRoute: OtomoCallActiveRoute,
  OtomoCallSummaryRoute: OtomoCallSummaryRoute,
  OtomoDashboardRevenueRoute: OtomoDashboardRevenueRoute,
  OtomoScheduleRoute: OtomoScheduleRoute,
  OtomoReviewsRoute: OtomoReviewsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminUsersRoute: AdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
